<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAAV3iO1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAAV3iO1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAAV3iO1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAAV3iO1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAAV3iO1\App_KernelDevDebugContainer([
    'container.build_hash' => 'AAV3iO1',
    'container.build_id' => '9ab6abd7',
    'container.build_time' => 1581427622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAAV3iO1');
